# Generated by Django 3.2.7 on 2022-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='datetime',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
